name: Terraform Validate with Conditional Logs

on:
  push:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform fmt check
        id: fmt
        run: terraform fmt -check -diff

      - name: Save formatting diff
        if: failure() && steps.fmt.outcome == 'failure'
        run: |
            terraform fmt -diff > fmt-diff.txt || true

      - name: Upload fmt diff
        if: failure() && steps.fmt.outcome == 'failure'
        uses: actions/upload-artifact@v6
        with:
            name: terraform-fmt-diff
            path: fmt-diff.txt