name: Terraform CI - Step Level Env

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-south-1

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      TF_VAR_environment: test

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - name: Terraform Plan ( With Trace Verbosity)
        env:
          TF_LOG: TRACE
        run: terraform plan
      - name: Terraform Plan ( Default Verbosity)
        env:
          TF_LOG: TRACE
        run: terraform plan